### ISSUE TITLE
Duplicated effort with https://github.com/tarsius/elisp-maintainers ?

### ISSUE THREAD

**Issue by Fuco1** [tareefdev/lets-support-emacs#2]
Hey.  I think this already exists :)  Thanks for setting it up anyway, means a lot that people use their time to help us support us ! :heart: 

https://github.com/tarsius/elisp-maintainers

**Comment by tareefdev** [comment]
Hi @Fuco1 :)
Yes, I'll join my forces to Trasius's initiative, see here:
https://github.com/tarsius/elisp-maintainers/issues/11

**Comment by Fuco1** [comment]
Thanks!
